# GitLab CI — README Injection Scan
#
# Add this to your .gitlab-ci.yml or include it as a template.
#
# Option A: Docker image (no setup needed)
# Option B: pip-less — just copy injection_scan.py into your repo

# --- Option A: Docker ---
injection-scan:
  stage: test
  image: ghcr.io/bountyyfi/injection-scan:v1
  variables:
    SCAN_PATH: "."
    SCAN_RECURSIVE: "true"
    SCAN_FAIL_ON: "critical"
    # SCAN_EXCLUDE: "vendor,third_party"
  script:
    - /opt/injection-scan/entrypoint.sh
  rules:
    - changes:
        - "**/*.md"
        - "**/*.markdown"
        - "**/*.rst"
        - "**/*.txt"
        - "**/*.html"
        - "**/*.htm"

# --- Option B: standalone script (no Docker) ---
# injection-scan:
#   stage: test
#   image: python:3.11-slim
#   script:
#     - python3 injection_scan.py . -r --fail-on critical
#   rules:
#     - changes:
#         - "**/*.md"
