name: README Injection Scan

on:
  push:
    paths: ['**.md', '**.markdown', '**.rst', '**.txt', '**.html', '**.htm']
  pull_request:
    paths: ['**.md', '**.markdown', '**.rst', '**.txt', '**.html', '**.htm']
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  injection-scan:
    name: Scan for AI-unsafe documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run README Injection Scan
        uses: bountyyfi/invisible-prompt-injection@v1
        with:
          path: '.'
          recursive: 'true'
          fail-on: 'critical'
          # exclude: 'test/fixtures,examples'  # optional
